-- Add lyrics column to combined_media and combined_media_library tables
-- This allows us to store and retrieve lyrics for tracks displayed in Explore, Library, and Profile pages

-- Add to combined_media table (public explore/profile view)
ALTER TABLE public.combined_media 
ADD COLUMN IF NOT EXISTS lyrics TEXT;

-- Add to combined_media_library table (user's private library)
ALTER TABLE public.combined_media_library 
ADD COLUMN IF NOT EXISTS lyrics TEXT;

-- Create index for lyrics search (optional, for future lyrics search feature)
CREATE INDEX IF NOT EXISTS idx_combined_media_lyrics 
  ON public.combined_media USING gin(to_tsvector('english', lyrics));

-- Comments for documentation
COMMENT ON COLUMN public.combined_media.lyrics IS 'Song lyrics for audio tracks. Can be generated by AI or user-provided.';
COMMENT ON COLUMN public.combined_media_library.lyrics IS 'Song lyrics for audio tracks. Can be generated by AI or user-provided.';
