-- RUN THIS ON PRODUCTION SUPABASE SQL EDITOR
-- Adds metadata columns to combined_media table

ALTER TABLE public.combined_media 
ADD COLUMN IF NOT EXISTS audio_prompt TEXT,
ADD COLUMN IF NOT EXISTS image_prompt TEXT,
ADD COLUMN IF NOT EXISTS is_published BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS genre TEXT,
ADD COLUMN IF NOT EXISTS mood TEXT,
ADD COLUMN IF NOT EXISTS tags TEXT[] DEFAULT '{}',
ADD COLUMN IF NOT EXISTS description TEXT,
ADD COLUMN IF NOT EXISTS bpm INTEGER,
ADD COLUMN IF NOT EXISTS vocals TEXT,
ADD COLUMN IF NOT EXISTS language TEXT;
