name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: Run ESLint
        run: npm run lint

  typecheck:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: Run TypeScript typecheck
        run: npm run typecheck

  build:
    runs-on: ubuntu-latest
    needs: [lint, typecheck]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: Build
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
        run: npm run build

  migrate:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: Run DB migrations
        env:
          PG_CONNECTION_STRING: ${{ secrets.PG_CONNECTION_STRING }}
        run: |
          if [ -z "$PG_CONNECTION_STRING" ]; then
            echo "PG_CONNECTION_STRING not set — skipping migrations"
          else
            npm run migrate
          fi

  deploy:
    name: Deploy to Vercel
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Vercel Production
        uses: amondnet/vercel-action@v25
        id: vercel-deploy
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--prod'
        continue-on-error: true
      - name: Deployment Status
        run: |
          if [ "${{ steps.vercel-deploy.outcome }}" == "success" ]; then
            echo "✅ Deployment successful!"
          else
            echo "⚠️ Deployment skipped or failed. This is expected if Vercel secrets are not configured."
            echo "To enable automatic deployments:"
            echo "1. Add VERCEL_TOKEN to repository secrets"
            echo "2. Add VERCEL_ORG_ID to repository secrets"
            echo "3. Add VERCEL_PROJECT_ID to repository secrets"
            echo ""
            echo "Alternative: Connect this repository to Vercel via their Git integration for automatic deployments."
          fi
